### ISSUE TITLE
TabView selection worked. when tabItem not display in bottom. 

### ISSUE THREAD

**Issue by ParasiOS** [bhumika-ios/SideBar#1]

**Comment by bhumika-ios** [comment]
Please provide more details, share your code

**Comment by ParasiOS** [comment]
<img width="355" alt="Screenshot 2023-07-05 at 7 25 34 AM" src="https://github.com/bhumika-ios/SideBar/assets/103592160/951180d7-f7c9-48b6-96b8-4f85394b557f">

Issues was there Tab Item Not display. but TabView selection was working. In case need to hide TabView.

**Comment by bhumika-ios** [comment]
Hi @parasdharasanda90 

can you please create pull request for tabview

**Comment by bhumika-ios** [comment]
check update repo
